<?php
$corpus = array('At times I feel like I understand everything. It is surprising how little good that does in itself. I become enclosed in my self: truth is smaller than reality.',
'Understanding is like a drug.',
'I want to show my desire for awesomeness. ',
'I have an intense interest in epistomology and mathematical linguistics, but talking about that somehow only makes sense when I put on shiny pants. Meaning is performative.',
'The processes I show are often closed loops.',
'Investigating my desire for awesomeness means substantiating my desire for awesomeness.',
'There are less words than things.',
'There are times when I feel like I won the game of rhetorics.',
'I like tight pants and mathematics.',
'I found, not only is meaning a sensation, it is a sensation that can approach the ecstatic.',
'At times I understand everything ',
'I want to deal with truth as a self-substantiating mechanism, with understanding as a self contained feedback loop. I want to chart and model the mental mechanisms of meaning.',
'In this light I see my work?',
'My desire for awesomeness is an absolute desire: a desire with no other end than itself.',
'Attempted to analyse my desire for awesomeness and got completely caught up in substantiating it.',
'Found awesomeness to be the modern day equivalent of the sublime.',
'Charting and modeling the mental mechanisms of meaning.');